plugins { id 'com.android.application' }

android {
    namespace 'com.walter.betanocompanion'
    compileSdk 35

    defaultConfig {
        applicationId 'com.walter.betanocompanion'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '1.4'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
